### PR TITLE
add support for date format

### PR DESCRIPTION
**Pull request by fuhrysteve**
At a glance it looks like this is all that would be needed see #19

### CODE REVIEW

**Comment by idelvall** [comment]
Thanks Steven, the reason I have not included it in the past is date representation has not be standardized for JSON (http://stackoverflow.com/questions/10286204/the-right-json-date-format). I'll think more on this matter and tell you.  
Thanks!

**Comment by fuhrysteve** [comment]
Thanks for taking a look @idelvall ! I have some philosophical thoughts on the matter if you will entertain me for a moment:

It seems to me that date representation decisions fall at least mostly outside of the scope of mere form rendering.

The JSON Schema documentation does state 

>  A string instance is valid against this attribute if it is a valid date representation as defined by RFC 3339, section 5.6 [RFC3339]. [link](http://json-schema.org/latest/json-schema-validation.html#anchor108)

However is it really within the scope of json-forms to do anything with that information? The responsibility ultimately seems to fall to the client to conform, and not the rendering library.

That said - it _might_ be appropriate for json-forms to decide what to put into the element when someone passes form data into `render`. What if, for instance, one application decides to pass a `Date()` object, and another decides to put in a string? My thought on the matter is that the JSON Schema specification does NOT say `"type": Date` but rather it EXPLICITLY states `"type": "string"`. If json-form were to decide to support `bf.render({start: new Date(999)})`, that it would be supporting what is essentially an invalid type (not saying it would be a bad idea - just invalid).

Anyways - Interestingly enough, the HTML5 specification seems to agree on RFC3339:

https://www.w3.org/TR/html-markup/datatypes.html#form.data.date

In any case, I would suggest that if you choose to support my proposal to render `format: "date"` => `<input type="date">`, that json-forms should take no opinion on the matter. The JSON Schema spec states that the type is a string, and it should be outside the scope of rendering to get involved in the matter. If it acts like a string, accept it and let the client live with the consequences.

Thanks again for your consideration!

**Comment by idelvall** [comment]
Excellent argumentation!
that was exactly what I wanted to look into, what the JSON spec says about `date` format and what the HTML 5 says about the data generated by the input. 
Thanks mate

**Comment by idelvall** [comment]
I am wondering that maybe it would be more correct to use `date-time` for the format attribute and `datetime` for input type, don't you think?

**Comment by idelvall** [comment]
Finally I added support for standard format `date-time`, rendering it in a `<input type="datetime-local">` (that has more support than `type="datetime"`)

**Comment by fuhrysteve** [comment]
Good question. I really struggled to find consistent info on that point, and struggled again when looking into it again now.

It seems that `"date"` either is or was a part of the spec at some point - maybe draft v3? But it clearly only mentions `date-time` now.

Both seem useful from my perspective. `date` certainly is more widely used in web forms.

I opted to support both in my implementation of a JSON Schema serializer for two reasons.

1. It's useful
2. The jsonschema draft v4 validator I use considers it "valid" to do so, as you can see here:

- [date definition](https://github.com/fuhrysteve/marshmallow-jsonschema/blob/master/tests/__init__.py#L37)
- [date serialization](https://github.com/fuhrysteve/marshmallow-jsonschema/blob/master/marshmallow_jsonschema/base.py#L31)
- [unit test validation](https://github.com/fuhrysteve/marshmallow-jsonschema/blob/master/tests/__init__.py#L37))


I suppose I'd suggest one of two, or both approaches:

1. support both (because it's useful to)
2. if there's a format specified with a string, just throw it in `data-format="date"` or `data-format="blah"` (or whatever the user decides to put in)



Here is an interesting tidbit I dug up about `format` in the spec:

http://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-7


> The value of this keyword is called a format attribute.  It MUST be a
>    string.  A format attribute can generally only validate a given set
>    of instance types.  If the type of the instance to validate is not in
>    this set, validation for this format attribute and instance SHOULD
>    succeed.

**Comment by idelvall** [comment]
Yes, the second option is exactly what I was considering to implement since we should not include any non-standard feature into the library. 

I see the way to go is giving the user the possibility of choosing the input type given a format attribute overriding the default behavior or moreover, the whole input creation.

I'll keep you informed of my advances...

**Comment by idelvall** [comment]
Hello Stephen. Today I have experienced the need to maintain a good documentation... The things is that I already had implemented this but I didn't remember it.

In order to override custom input type you can use: [BrutusinForms.bootstrap.addFormatDecorator(...)](https://github.com/brutusin/json-forms/blob/master/src/js/brutusin-json-forms-bootstrap.js#L127)

If you don't use the `brutusin-json-forms-bootstrap.js` extension, you can reuse this function code removing the glyphicon part.

New examples showing this functionality :
http://brutusin.org/json-forms/#9

**Comment by fuhrysteve** [comment]
Wow - I saw that function when I was poking around, but I must have misunderstood what it was for. Thanks for adding the docs! That's exactly what I'll use.

**Pull request merged**
