### PR TITLE
Adding handler for definitions and internal $refs. 

### PR DESCRIPTION
**Pull request by ocschwar**
This simple change populates the schemaMap with a copy of a definition where ever one is referred to with a $ref.

### CODE REVIEW

**Comment by idelvall** [comment]
Hi Omri,
could you add an example to [index.html](https://github.com/brutusin/json-forms/blob/gh-pages/index.html) showing the new functionality?
Thanks!

**Comment by ocschwar** [comment]
Done. 

Also, my fork now has a handler for patternProperties too, as well as greying out for elements marked readOnly. (basic types are greyed out, and array types marked as "readOnly" have the addButton and removeButtons greyed out. Not sure how or whether to do the same with objects and one's.

**Comment by idelvall** [comment]
Hi Omri, excuse the delay, I have been very busy lately... First of all thank you for your contributions!
I am working on it now

**Comment by idelvall** [comment]
Hi Omri, I've just merged your PR.
I did some minor refactoring so you should merge your code to align ourselves.

The readonly implementation (http://brutusin.org/json-forms/#12) seems to be unfinished. Shouldn't the input values be also disabled? I think so.

I open a new issue for it 
https://github.com/brutusin/json-forms/issues/26

**Pull request merged**
